# Generated by Django 3.2.20 on 2023-09-05 00:08

from django.db import migrations, models
import django.db.models.deletion
import lhlmsApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null='True', unique=True)),
                ('Genres', models.CharField(max_length=200, null='True')),
                ('date_of_birth', models.DateTimeField(auto_now_add=True, null='True')),
                ('date_of_death', models.DateTimeField(auto_now_add=True, null='True')),
                ('spouse', models.CharField(max_length=200, null='True')),
                ('other_achievements', models.CharField(max_length=200, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null='True', unique=True)),
                ('city_of_origin', models.CharField(max_length=200, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null='True')),
                ('ID_no', models.IntegerField(null='True', unique=True, validators=[lhlmsApp.models.person_id])),
                ('reg_no', models.PositiveIntegerField(null='True', unique=True, validators=[lhlmsApp.models.staff_reg_no])),
                ('age', models.PositiveIntegerField(null='True', validators=[lhlmsApp.models.other_age])),
                ('role', models.CharField(choices=[('Warden', 'Warden'), ('Security guard', 'Security guard'), ('Developer', 'Developer'), ('Stock management', 'Stock management'), ('Secretary', 'Secretary')], max_length=200, null='True')),
                ('email', models.CharField(blank=True, max_length=60, null='True')),
                ('phone_no', models.IntegerField(null='True', validators=[lhlmsApp.models.phone])),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null='True')),
                ('form', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=200, null='True')),
                ('stream', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=200, null='True')),
                ('reg_no', models.IntegerField(null='True', unique=True, validators=[lhlmsApp.models.stud_reg_no])),
                ('age', models.PositiveIntegerField(null='True', validators=[lhlmsApp.models.stud_age])),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null='True', unique=True)),
                ('Genres', models.CharField(max_length=200, null='True')),
                ('Serial_no', models.IntegerField(null='True', unique=True, validators=[lhlmsApp.models.book_serial_no])),
                ('year_of_publication', models.IntegerField(null='True', validators=[lhlmsApp.models.year_lenght])),
                ('publisher', models.CharField(max_length=200, null='True')),
                ('pages', models.IntegerField(null='True', validators=[lhlmsApp.models.page_lenght])),
                ('status', models.CharField(choices=[('Pending Order', 'Pending Order'), ('Delivered Order', 'Delivered Order')], max_length=200, null='True')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lhlmsApp.author_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Book_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null='True')),
                ('date_of_order', models.DateTimeField(auto_now_add=True, null='True')),
                ('status', models.CharField(choices=[('Pending Order', 'Pending Order'), ('Delivered Order', 'Delivered Order')], max_length=200, null='True')),
                ('book_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lhlmsApp.books')),
                ('publisher_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lhlmsApp.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Book_borrowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_borrow', models.DateTimeField(auto_now_add=True, null='True')),
                ('date_of_return', models.DateTimeField(auto_now_add=True, null='True')),
                ('books_borrowed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lhlmsApp.books')),
                ('stud_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lhlmsApp.student')),
            ],
        ),
    ]
