# Generated by Django 3.2.20 on 2023-09-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhlmsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='in_stock',
            field=models.PositiveIntegerField(null='True'),
            preserve_default='True',
        ),
    ]
