# Generated by Django 3.2.20 on 2023-09-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhlmsApp', '0002_books_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author_detail',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='author_detail',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='books',
            name='status',
        ),
        migrations.AddField(
            model_name='book_borrowed',
            name='issue_fine',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='author_detail',
            name='other_achievements',
            field=models.CharField(blank=True, max_length=200, null='True'),
        ),
        migrations.AlterField(
            model_name='author_detail',
            name='spouse',
            field=models.CharField(blank=True, max_length=200, null='True'),
        ),
        migrations.AlterField(
            model_name='book_orders',
            name='quantity',
            field=models.PositiveIntegerField(null='True'),
        ),
    ]
