# Generated by Django 3.2.20 on 2023-09-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhlmsApp', '0003_auto_20230906_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_borrowed',
            name='issue_fine',
        ),
        migrations.AddField(
            model_name='staff',
            name='sex',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=200, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=200, null='True'),
            preserve_default='True',
        ),
    ]
